from typing import Optional
from davos.core.config import IpythonShell

def _check_conda_avail_helper() -> Optional[str]: ...
def _run_shell_command_helper(command: str) -> None: ...
def _set_custom_showsyntaxerror() -> None: ...
def _showsyntaxerror_davos(
        ipy_shell: IpythonShell,
        filename: Optional[str] = ...,
        running_compiled_code: bool = ...
) -> None: ...
