from davos.core.config import IpythonShell

__all__ = list[str]

def _check_conda_avail_helper() -> str | None: ...
def _run_shell_command_helper(command: str) -> None: ...
def _set_custom_showsyntaxerror() -> None: ...
def _showsyntaxerror_davos(ipy_shell: IpythonShell, filename: str | None = ...,
                           running_compiled_code: bool = ...) -> None: ...
