from typing import Literal, TypeVar
from davos.core.core import SmuggleFunc
from davos.implementations import IPyPost7FullParserFunc, LineParserFunc

__all__ = list[Literal['generate_parser_func']]

def _activate_helper(smuggle_func: SmuggleFunc, parser_func: IPyPost7FullParserFunc) -> None: ...
def _deactivate_helper(smuggle_func: SmuggleFunc, parser_func: IPyPost7FullParserFunc) -> None: ...
def generate_parser_func(line_parser: LineParserFunc) -> IPyPost7FullParserFunc: ...
