from davos.implementations import ParserFunc, SmuggleFunc

# TODO: add __all__

def _activate_helper(smuggle_func: SmuggleFunc, parser_func: ParserFunc) -> None: ...
def _deactivate_helper(smuggle_func: SmuggleFunc, parser_func: ParserFunc) -> None: ...