from typing import Literal
from davos.implementations import LineParserFunc, SmuggleFunc

__all__ = list[Literal['generate_parser_func']]

def _activate_helper(smuggle_func: SmuggleFunc, parser_func: LineParserFunc) -> None: ...
def _deactivate_helper(smuggle_func: SmuggleFunc, parser_func: LineParserFunc) -> None: ...
def generate_parser_func(line_parser: LineParserFunc) -> LineParserFunc: ...