from collections.abc import Callable
from typing import Literal, Optional
from davos.implementations import LineParserFunc, SmuggleFunc

__all__ = list[Literal['generate_parser_func']]

PyFullParserFunc = Callable[[list[str]], list[str]]

def _activate_helper(smuggle_func: SmuggleFunc, parser_func: LineParserFunc) -> None: ...
def _check_conda_avail_helper() -> Optional[str]: ...
def _deactivate_helper(smuggle_func: SmuggleFunc, parser_func: LineParserFunc) -> None: ...
def _run_shell_command_helper(command: str) -> None: ...
def generate_parser_func(line_parser: LineParserFunc) -> PyFullParserFunc: ...