from pathlib import PosixPath
from typing import Literal, NoReturn

__all__ = list[Literal['Project', 'get_notebook_path', 'use_default_project']]

DAVOS_CONFIG_DIR: PosixPath
DAVOS_PROJECT_DIR: PosixPath
PATHSEP: Literal['/', '\\']
PATHSEP_REPLACEMENT: Literal['___']
SITE_PACKAGES_SUFFIX: str

class ProjectChecker(type):
    def __call__(cls, name: PosixPath | str) -> AbstractProject | ConcreteProject: ...

class Project(metaclass=ProjectChecker):
    _installed_packages: list[tuple[str, str]]
    _site_packages_mtime: float
    name: str
    safe_name: str
    project_dir: PosixPath
    site_packages_dir: PosixPath
    def __init__(self, name: str) -> None: ...
    def __del__(self) -> None: ...
    def __repr__(self) -> str: ...
    @property
    def installed_packages(self) -> list[str]: ...
    def _refresh_installed_pkgs(self) -> None: ...
    def freeze(self) -> str: ...
    def remove(self, yes: bool = ...) -> None: ...
    def rename(self, new_name: PosixPath | str) -> NoReturn: ...

class AbstractProject(Project):
    def __repr__(self) -> str: ...

class ConcreteProject(Project): ...

def _filepath_to_safename(filepath: str) -> str: ...
def _safename_to_filepath(safename: str) -> str: ...

def cleanup_project_dir_atexit(dirpath: PosixPath) -> None: ...
def prune_project(proj: ConcreteProject | PosixPath | str) -> NoReturn: ...
def prune_projects() -> NoReturn: ...
def use_default_project() -> None: ...
