name: CI Tests

#on: [push, pull_request]
on:
  push:
    paths-ignore:
      - 'paper/**'
      - '.gitattributes'
      - 'LICENSE'
      - 'README.md'
  pull_request:
    paths-ignore:
      - 'paper/**'
      - '.gitattributes'
      - 'LICENSE'
      - 'README.md'
  workflow_dispatch: 
    inputs: 
      debug_enabled:
        description: 'Pause before tests for tmate debugging'
        required: false
        default: 'false'
      notebook_type:
        description: 'Job type to debug {colab|jupyter|all}'
        required: false
        default: 'all'

defaults:
  run:
    shell: bash -leo pipefail {0}

jobs:
  run-tests:
    name: "Run CI tests (${{ matrix.notebook-type }}, Python ${{ matrix.python-version }}, IPython ${{ matrix.ipython-version }})"
    runs-on: ubuntu-latest
    # only run on pull requests between forks to avoid duplicate runs with 'push' event
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    strategy:
      fail-fast: false
      matrix:
        include:
          - notebook-type: jupyter
            python-version: 3.6
            ipython-version: 5.5.0
          - notebook-type: jupyter
            python-version: 3.6
            ipython-version: 7.16    # latest version to support Python 3.6
          - notebook-type: jupyter
            python-version: 3.7
            ipython-version: 5.5.0
          - notebook-type: jupyter
            python-version: 3.7
            ipython-version: latest
          - notebook-type: jupyter
            python-version: 3.8
            ipython-version: 7.3.0    # earliest version to support Python 3.8
          - notebook-type: jupyter
            python-version: 3.8
            ipython-version: latest
          - notebook-type: jupyter
            python-version: 3.9
            ipython-version: 7.15     # earliest version to support Python 3.9
          - notebook-type: jupyter
            python-version: 3.9
            ipython-version: latest
          - notebook-type: colab
            python-version: 3.7       # I/Python versions are arbitrary for Colab-based
            ipython-version: 5.5.0    # tests. Chosen to denote versions Colab uses
    env:
      NOTEBOOK_TYPE: ${{ matrix.notebook-type }}
      PYTHON_VERSION: ${{ matrix.python-version }}
      IPYTHON_VERSION: ${{ matrix.ipython-version }}
      GMAIL_ADDRESS: ${{ secrets.DAVOS_GMAIL_ADDRESS }}
      GMAIL_PASSWORD: ${{ secrets.DAVOS_GMAIL_PASSWORD }}
      RECOVERY_GMAIL_ADDRESS: ${{ secrets.DAVOS_RECOVERY_GMAIL_ADDRESS }}
      HEAD_SHA: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.sha }}
    steps:
      - uses: actions/checkout@v2

      - name: install miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          auto-activate-base: true
          activate-environment: ""

      - name: setup base environment
        run: |
          # install Python 3.9 (used to run notebooks via selenium, not the tests themselves)
          conda install python=3.9
          
          # install Firefox browser
          sudo apt-get install firefox
          
          # install python packages
          pip install pytest==6.2 "selenium>=3.141" geckodriver-autoinstaller
          
          # install geckodriver
          driver_path=$(python -c '
          
          import shutil
          from pathlib import Path
          
          import geckodriver_autoinstaller
          
          driver_src = Path(geckodriver_autoinstaller.install(cwd=True))
          driver_dest = driver_src.rename(driver_src.parents[1].joinpath(driver_src.name))
          driver_src.parent.rmdir()
          print(driver_dest)
          
          ')
          
          # export path to driver as environment variable
          echo "DRIVER_PATH=$driver_path" >> $GITHUB_ENV

      - name: setup notebook kernel environment
        if: matrix.notebook-type == 'jupyter'
        run: |
          # install jupyter notebooks application in base environment
          pip install notebook "ipykernel>=5.0.0"
          
          # create kernel environment
          conda create -n kernel-env python=$PYTHON_VERSION          
          
          # install davos & various test requirements in kernel environment
          conda activate kernel-env
          if [[ "$PYTHON_VERSION" =~ ^3.(6|7)$ ]]; then
              pip install typing-extensions
          fi
          if [[ "$IPYTHON_VERSION" == "latest" ]]; then
              pip install --upgrade IPython
          else
              pip install IPython==$IPYTHON_VERSION
          fi
          pip install \
              "ipykernel>=5.0.0" \
              requests \
              scipy \
              fastdtw==0.3.4 \
              tqdm==4.41.1 \
              numba==0.51.2
          pip install .

          # make environment available as a jupyter kernel
          python -m ipykernel install --prefix=/usr/share/miniconda --name=kernel-env
          conda deactivate
          
      - name: launch Jupyter server
        if: matrix.notebook-type == 'jupyter'
        run: jupyter notebook --no-browser --port=8888 --NotebookApp.token= &

      - name: debug runner
        if: |
          github.event_name == 'workflow_dispatch'
          && github.event.inputs.debug_enabled == 'true'
          && (matrix.notebook-type == 'all' || matrix.notebook-type == github.event.inputs.notebook_type)
        uses: mxschmitt/action-tmate@v3

      - name: run pytest
        run: pytest -sv tests/

      - name: upload selenium error artifact
        if: env.ERROR_PAGE_SOURCE != ''
        uses: actions/upload-artifact@v2
        with:
          name: error-page-source
          path: ${{ env.ERROR_PAGE_SOURCE }}
