name: Request Colab Tests for PR

on:
  pull_request_target:
    paths-ignore:
      - 'paper/**'
      - '.gitattributes'
      - 'LICENSE'
      - 'README.md'

defaults:
  run:
    shell: bash -leo pipefail {0}

jobs:
  request-colab-tests:
    name: "Request approval to run Colab tests"
    runs-on: ubuntu-latest
    if: github.repository == 'ContextLab/davos' && github.event.pull_request.head.repo.full_name != 'ContextLab/davos'
    env:
      BASE_REPO: ${{ github.repository }}
      HEAD_REPO: ${{ github.event.pull_request.head.repo.full_name }}
      HEAD_SHA: ${{ github.event.pull_request.head.sha }}
    steps:
      - name: Comment on PR
        uses: actions/github-script@v4
        with:
          script: |
            const headRepo = process.env.HEAD_REPO,
                headSha = process.env.HEAD_SHA,
                headShaShort = headSha.substr(0, 7),
                headCommitUrl = `https://github.com/${headRepo}/tree/${headSha}`,
                commentBody = `@paxtonfitzpatrick Run Colab CI tests on [${headRepo}@${headShaShort}?](${headCommitUrl})?`;

            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: commentBody;
            })
